#### Numpy Exercises

In [2]:
import numpy as np

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

##### Checking that the sudoku is valid or not and gor valid sudoku sum of rows should br 45 and sum of columns dhold be 45 and the block of 3 columns and rows should be 45.

##### so first we will check rows and column 

In [6]:
rows = np.sum(s, axis = 1) # for rows axis = 1
rows

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [7]:
columns = np.sum(s, axis = 0)
columns

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

#### Slicing

In [9]:
s[0:3,0:3],s[3:6,3:6],s[6:9,6:9]

(array([[5, 3, 4],
        [6, 7, 2],
        [1, 9, 8]]),
 array([[7, 6, 1],
        [8, 5, 3],
        [9, 2, 4]]),
 array([[2, 8, 4],
        [6, 3, 5],
        [1, 7, 9]]))

In [10]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [11]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


### General Questions

In [13]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

#### Get the shape of the matrix.

In [15]:
data.shape

(5, 3)

#### Find the average age of students.

In [17]:
np.mean(data[:,0])

18.4

#### Extract Math marks of all students.

In [19]:
data[:,1]

array([85, 92, 76, 65, 90])

#### Find the highest Science mark.

In [21]:
np.max(data[0:2])

92

#### Get details of the student who scored more than 90 in Math.

In [23]:
data[data[:,1] > 90]

array([[19, 92, 88]])

#### Increase Math marks of all students by 5.

In [25]:
data[:,1] + 5 

array([90, 97, 81, 70, 95])

#### Find how many students are younger than 19.

In [27]:
# a = data[:,0] < 19
# np.sum(a)

len(data[data[:,0] < 19])

3

#### Calculate the average marks in each subject (column-wise mean).

In [29]:
# math_avg = np.mean(data[:,1])
# sci_avg = np.mean(data[:,2])
# math_avg,sci_avg

np.mean(data[:,1:], axis = 0)

array([81.6, 83.2])

#### Get data of students who scored at least 80 in both subjects.

In [31]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [32]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

#### Replace all Science marks < 75 with 0.

In [34]:
data[:,2][data[:,2] < 75] = 0 
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])