In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
a = np.array([[55,8,77],[69,23,88]])
b = np.random.random((3,3))
c = np.ones((5,5))

print(a)
print(b)
print(c)

[[55  8 77]
 [69 23 88]]
[[0.50882932 0.99090223 0.02778595]
 [0.41445978 0.72119962 0.45174536]
 [0.55891511 0.39683472 0.03606623]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### save and load files 

In [10]:
n = np.save("a.npy", a)
n = np.save("b.npy", b)
n = np.save("c.npy", c)

In [13]:
print(np.load("a.npy"))
print(np.load("b.npy"))
print(np.load("c.npy"))

[[55  8 77]
 [69 23 88]]
[[0.50882932 0.99090223 0.02778595]
 [0.41445978 0.72119962 0.45174536]
 [0.55891511 0.39683472 0.03606623]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### dark mode conversion