### Operations on NUMPY Array


In [2]:
import numpy as np

#### Basic Slicing 1D

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing ",arr)
print("Basic Slicing ",arr[2:7])
print("Basic Slicing with steps ",arr[1:8:2])
print("Basic Slicing with negative slicing ",arr[-6])

Basic Slicing  [ 1  2  3  4  5  6  7  8  9 10]
Basic Slicing  [3 4 5 6 7]
Basic Slicing with steps  [2 4 6 8]
Basic Slicing with negative slicing  5


#### Slicing 2D array

In [6]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print("Specific Element ",arr_2d[1,2])
print("Entire row ",arr_2d[2])
print("Entire column ",arr_2d[:,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element  6
Entire row  [7 8 9]
Entire column  [2 5 8]


#### Sorting 1D

In [23]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Basic Array ",np.sort(unsorted))

Basic Array  [1 1 2 3 4 5 6 9]


#### Sorting 2D

In [10]:
arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print(arr_2d_unsorted)
print("2D array axis 0 --> column",np.sort(arr_2d_unsorted, axis = 0))
print("2D array axis 1 --> row",np.sort(arr_2d_unsorted, axis = 1))


[[3 1]
 [1 2]
 [2 3]]
2D array axis 0 --> column [[1 1]
 [2 2]
 [3 3]]
2D array axis 1 --> row [[1 3]
 [1 2]
 [2 3]]


#### Filtering Array

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Number greater than 5", even_numbers)


# Filter with MASK --> mask is an expression which is doing evaluation
mask = numbers>5
print("Number greater than 5 with mask",numbers[mask])

Number greater than 5 [ 2  4  6  8 10]
Number greater than 5 with mask [ 6  7  8  9 10]


#### Fancy Indexing VS np.where()

In [21]:
# indices of numbers and it will give number on that index.
indices = [0,3,4]
print(numbers[indices])

#where
where_result = np.where(numbers>5)
print("where_result --> it will give indices of the result", where_result) # --> it will give indices 
print("where_result --> it will give actual where result",numbers[where_result])


#condition_array
#numbers > 5 is condition
#numbers * 4 is what will happen if it is true
#numbers is what will happen if it is false
#it gives entire array with results...
condition_array = np.where(numbers > 5, numbers * 4, numbers)
print(condition_array)
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

[1 4 5]
where_result --> it will give indices of the result (array([5, 6, 7, 8, 9]),)
where_result --> it will give actual where result [ 6  7  8  9 10]
[ 1  2  3  4  5 24 28 32 36 40]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


#### Adding and removing DATA --> concatenate, vstack,hstack

In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combine = arr1 + arr2
print(combine)

combined = np.concatenate((arr1,arr2))
print(combined)

[5 7 9]
[1 2 3 4 5 6]


#### Array compatibilityyy

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [37]:
# add new row
og = np.array([[1,2],[4,5]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((og,new_row))
print("with_new_row : ",with_new_row)



with_new_row :  [[1 2]
 [4 5]
 [5 6]]


In [40]:
# add new column
og_col= np.array([[1,2],[4,5]])
new_col = np.array([[5],[6]])
with_new_col = np.hstack((og_col,new_col))
print("with_new_col : ",with_new_col)

with_new_col :  [[1 2 5]
 [4 5 6]]


#### Delete operation

In [8]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("After deleting element : ",deleted)

arr_2_d = np.array([[1,2,2,2,5],[1,2,3,4,5]])
print(arr_2_d)
new_2d = np.delete(arr_2_d,3,axis = 1)
print("After deleting element in 2d array: ",new_2d)

After deleting element :  [1 2 4 5]
[[1 2 2 2 5]
 [1 2 3 4 5]]
After deleting element in 2d array:  [[1 2 2 5]
 [1 2 3 5]]


#### spliting 

In [16]:
x = np.array([1,2,3,4,5])
print(x)
xy = np.split(x, 5)
print("\nnormal split",xy)


y = np.array([[91,28,25,27,50,88],[41,62,33,84,57,99]])
print("\n 2d array : \n",y)
xyy = np.hsplit(y, 3)
print("\n hsplit --> column wise",xyy)
yy = np.vsplit(y, 2)
print("\n vsplit --> row wise",yy)




[1 2 3 4 5]

normal split [array([1]), array([2]), array([3]), array([4]), array([5])]

 2d array : 
 [[91 28 25 27 50 88]
 [41 62 33 84 57 99]]

 hsplit --> column wise [array([[91, 28],
       [41, 62]]), array([[25, 27],
       [33, 84]]), array([[50, 88],
       [57, 99]])]

 vsplit --> row wise [array([[91, 28, 25, 27, 50, 88]]), array([[41, 62, 33, 84, 57, 99]])]
