## Numpy Array and basics
 

In [1]:
import numpy as np

##### Check the vesion of numpy

In [25]:
#check the vesion of numpy
print(np.__version__)

2.2.4


#### creating array 

In [21]:
arr_1d = np.array([1,2,3,4,5,6,7])
print(arr_1d)

arr_2d = np.array([[1,2,3,4],[55,99,87,24]])
print(arr_2d)

[1 2 3 4 5 6 7]
[[ 1  2  3  4]
 [55 99 87 24]]


#### List VS Numpy Array

In [22]:
py_list = [1,2,3,4,5,6,7]
print("python list multiplication : ", py_list * 2) #

np_arr = np.array([1,2,3,4]) # this is matrix so element wise multiplication
print("python larrayist multiplication : ", np_arr * 2) #here 2 is scaler bcz constant ke sath multiply haii

import time
start = time.time()
python_list = [i*2 for i in range(1000000)]
print("\n list operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n np Array operation time : ", time.time() - start)

python list multiplication :  [1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]
python larrayist multiplication :  [2 4 6 8]

 list operation time :  0.11574769020080566

 np Array operation time :  0.005826234817504883


#### Array fromn scratch 

In [23]:
zeros = np.zeros((3,3))
print("Zeros : \n", zeros)

ones = np.ones((4,4))
print("ones : \n", ones)

full = np.full((5,5),3)
print("full : \n", full)

randomness = np.random.random((2,2))
print("randomness : \n", randomness)

sequence = np.arange(0,11,2)
print("sequence : \n", sequence)


Zeros : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full : 
 [[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
randomness : 
 [[0.2983462  0.80303808]
 [0.35956911 0.62430572]]
sequence : 
 [ 0  2  4  6  8 10]


#### Vector,Matrix,Tesnsor

In [ ]:
#One dimension array
vector = np.array([1,2,3])
print("vector : ",vector)

#2D array called matrix
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix : ",matrix)

#multiple dimension called tensor
tensor = np.array([[[1,2,3],[4,5,6]],
                   [[5,9,7],[6,8,1]]])
print("tensor : ",tensor)



vector :  [1 2 3]
matrix :  [[1 2 3]
 [4 5 6]]
tensor :  [[[1 2 3]
  [4 5 6]]

 [[5 9 7]
  [6 8 1]]]


#### Array Properties

In [29]:
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[1,2,3],[4,5,6.9]])
print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size : ", arr.size)
print("Data Type : ", arr.dtype)
print("Data Type : ", arr1.dtype)


Shape :  (2, 3)
Dimension :  2
Size :  6
Data Type :  int64
Data Type :  float64


#### Array Reshaping --> Reshape,Flatten, Ravel,Transpose

In [35]:
arr = np.arange(12)
print("Array : ",arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array : ",reshaped)

# flatten returns copy of Flattened array
Flattened = reshaped.flatten()
print("Flattened Array : ",Flattened)

# Ravel returns view of original array
raveled = reshaped.ravel()
print("Raveled Array : ",raveled)

transpose = reshaped.T
print("transposed Array : ",transpose)


Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed Array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [6]:
#identify matrices

identity = np.eye(4)
print(identity)


# change DATA TYPE

arr = np.array([[1.23,5.89],[7.99,98.32]])
print(arr)
print(arr.dtype)
changed_type = arr.astype(int)
print("changed_type is ", changed_type.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.23  5.89]
 [ 7.99 98.32]]
float64
changed_type is  int64
